name: Release

on:
  push:
    branches: [main]
    tags: ['v*.*.*']

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    environment: pypi
    permissions:
      contents: write
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install uv
        uses: astral-sh/setup-uv@v3
        with:
          version: "0.8.0"

      - name: Cache UV dependencies
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/uv
            .venv
          key: ${{ runner.os }}-uv-release-${{ hashFiles('**/pyproject.toml', '**/uv.lock') }}
          restore-keys: |
            ${{ runner.os }}-uv-release-

      - name: Install dependencies
        run: |
          uv sync --all-extras --all-groups

      - name: Check version consistency
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          uv run python tools/check_version_tag.py
      
      - name: Run quality checks  
        if: github.event_name != 'push' || !startsWith(github.ref, 'refs/tags/')
        run: |
          uv run ruff check .
          uv run pyright
          uv run pytest tests/unit/

      - name: Build package for tag release
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          uv run python -m build

      - name: Check package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        run: |
          uv run python -m twine check dist/*

      - name: Publish to PyPI
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          skip-existing: true

      - name: Create GitHub Release and Upload Assets
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
        uses: softprops/action-gh-release@v2
        with:
          files: dist/*
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          body: |
            Release ${{ github.ref_name }}
            
            Automated package published to PyPI with simplified middleware stack and documentation cleanup.
            
            ## Changes
            - Simplified middleware stack focusing on core rate limiting and debouncing
            - Streamlined storage backends (memory and Redis)
            - Documentation cleanup and restructuring
            - Performance improvements and benchmarks
          overwrite_files: true
          generate_release_notes: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

